### ISSUE TITLE
Problem loading extension on burp

### ISSUE THREAD

**Issue by Xoiph0s** [B-i-t-K/PwnFox#1]
Hi, i encountered this error when trying to load the extension.

![image](https://user-images.githubusercontent.com/36005760/83672913-a1577000-a609-11ea-87fc-4850adaaa4f3.png)

**Comment by B-i-t-K** [comment]
I've got no idea where this come from, can you send me your java version your burp version ?

**Comment by UpcLeo** [comment]
i had the the error,and my java version is "1.8.0_181" burp version is v2.0.11 beta
![图片](https://user-images.githubusercontent.com/52128534/83707699-2adc6180-a64d-11ea-902e-13d7d08e8ecd.png)
![图片](https://user-images.githubusercontent.com/52128534/83707643-0b453900-a64d-11ea-93fa-a40b78927887.png)
![图片](https://user-images.githubusercontent.com/52128534/83707670-17c99180-a64d-11ea-9b17-0157169bac9f.png)

**Comment by 0x6d69636b** [comment]
I get the same error message with _openjdk version "11.0.7-ea" 2020-04-14_ and _Burp Suite Professional v2020.4.1_

```java
java.lang.ClassNotFoundException: kotlin.TypeCastException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.gbx.a(Unknown Source)
	at burp.gbx.<init>(Unknown Source)
	at burp.gvv.a(Unknown Source)
	at burp.elq.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Xoiph0s** [comment]
My java version is 
![image](https://user-images.githubusercontent.com/36005760/83719400-97655980-a669-11ea-9118-88cddba937a2.png)

And burp version is
![image](https://user-images.githubusercontent.com/36005760/83719429-a3511b80-a669-11ea-9bdf-415c66eb894b.png)

**Comment by Hackndo** [comment]
Hello,

same error here, with release or build.sh version

![image](https://user-images.githubusercontent.com/11051803/83738068-1bace200-a654-11ea-9e9e-12c4e08941b7.png)

![image](https://user-images.githubusercontent.com/11051803/83738170-3c753780-a654-11ea-9a1a-85c270b95660.png)

**Comment by B-i-t-K** [comment]
I've updated the gradle.build, It should work fine now.

**Comment by Hackndo** [comment]
Yes, working now. Thanks!

**Comment by B-i-t-K** [comment]
Thanks for reporting the issue, closing now.
